USE [master]
GO

/****** Object:  Database [CBScreenCap]    Script Date: 3/4/2025 11:05:02 AM ******/
CREATE DATABASE [CBScreenCap]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CBScreenCap_Data', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\CBScreenCap_Data.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'CBScreenCap_Log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\CBScreenCap_Log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 1024KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CBScreenCap].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CBScreenCap] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CBScreenCap] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CBScreenCap] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CBScreenCap] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CBScreenCap] SET ARITHABORT OFF 
GO

ALTER DATABASE [CBScreenCap] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CBScreenCap] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CBScreenCap] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CBScreenCap] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CBScreenCap] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CBScreenCap] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CBScreenCap] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CBScreenCap] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CBScreenCap] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CBScreenCap] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CBScreenCap] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CBScreenCap] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CBScreenCap] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CBScreenCap] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CBScreenCap] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CBScreenCap] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CBScreenCap] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CBScreenCap] SET RECOVERY FULL 
GO

ALTER DATABASE [CBScreenCap] SET  MULTI_USER 
GO

ALTER DATABASE [CBScreenCap] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CBScreenCap] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CBScreenCap] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CBScreenCap] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CBScreenCap] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CBScreenCap] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CBScreenCap] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CBScreenCap] SET  READ_WRITE 
GO


USE [CBScreenCap]
GO

/****** Object:  Table [dbo].[Models]    Script Date: 3/4/2025 11:06:03 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Models](
	[ScreenName] [nvarchar](50) NULL,
	[Online] [nvarchar](50) NULL,
	[URL] [nvarchar](250) NULL,
	[PID] [nvarchar](50) NULL,
	[DoRecord] [int] NULL
) ON [PRIMARY]
GO




USE [CBScreenCap]
GO

/****** Object:  Table [dbo].[RecordLog]    Script Date: 3/4/2025 11:06:28 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RecordLog](
	[ScreenName] [nvarchar](250) NULL,
	[PID] [nvarchar](250) NULL,
	[FilePath] [nvarchar](250) NULL,
	[RecordStart] [nvarchar](250) NULL,
	[RecordEnd] [nvarchar](250) NULL,
	[Converted] [nvarchar](250) NULL,
	[ConversionPath] [nvarchar](250) NULL,
	[ConversionDate] [nvarchar](250) NULL
) ON [PRIMARY]
GO

